### ISSUE TITLE
Lock Down Master Branch

### ISSUE THREAD

**Issue by samgomena** [shared-systems/PLUTO#27]
As we come closer to a 'release candidate' we should lock down the master branch (and probably develop) to require pull requests and known contributors to be able to update it (them).

With that, we should start considering the master branch to effectively be _the_ 'release candidate' so to speak.

This can be done in the repository settings. I'll probably do this, but I wanted to give a heads up on here so everyone sees it!

**Comment by lixphilosophy** [comment]
I think we can have two option on this.
- Bring the application totally communicated with the server via Api, then make some fake value at the backend for presenting and testing purpose.
- just simple apply an 0 to integer variable and "-" for string variable, then claim that the function is unavailable in the current stage.
After we pick either of them and finish the job, we can lock the master for the current stage version.

**Comment by susham** [comment]
Yes, lets test the entire application on Saturday at 7:00 pm and fix as many bugs as we can then lock down the master and develop branch. 

There are few things we have to discuss like the branch from which the users can download the entire package and steps to execute the individual branches.

**Comment by samgomena** [comment]
I've added some additional permissions here. Specifically, `develop` and `master` now require their branches to be up to date with their respective origin as well as both require two PR reviewers before merging.

Doing this definitely covers what I had initially intended for this issue in the first place and, naturally, we can adjust these restrictions as we move forward.

**Comment by susham** [comment]
Can we lockdown the master branch this sunday?

**Comment by samgomena** [comment]
In short, yes, but is there a specific reason why you want to do so?

**Comment by susham** [comment]
I want everyone to test the master branch and not the develop branch.. So that the process of installing and using the DeepShare can be seamless which will help us out in rolling out the first version of DeepShare.

**Comment by samgomena** [comment]
Nothing I've done should prevent that process. If you want I can turn them off though.

**Comment by susham** [comment]
No, it’s not necessary to turn off the permissions
