### ISSUE TITLE
Remove all Console Logging

### ISSUE THREAD

**Issue by susham** [shared-systems/PLUTO#31]
After running PLUTO, once you login, you can see the login credentials being displayed on the console. Console logging should be avoided, need to come up with a better logging implementation at PLUTO end. An encrypted logging to a file?

**Comment by samgomena** [comment]
https://stackoverflow.com/questions/44475816/python-logging-module-encrypt

This may be something worth looking into. I imagine there's a couple libraries out there that do this as well.

**Comment by lixphilosophy** [comment]
fixed

**Comment by susham** [comment]
Right now there are a lot of `print(...)` statements strewn about in the codebase. These, at the very least should be removed, but preferably should be replaced with some sort of logging functionality.

**Comment by lixphilosophy** [comment]
fixed
