### ISSUE TITLE
Automatic retrieval of ipaddress shows localhost(127.0.0.1), but the actual ipaddress is different

### ISSUE THREAD

**Issue by susham** [shared-systems/PLUTO#41]
![screenshot from 2018-10-06 23-41-22](https://user-images.githubusercontent.com/5677583/46579193-6d095780-c9c1-11e8-8fce-facefa7c528e.png)

**Comment by susham** [comment]
OS: Ubuntu 18.04
Connected to internet
Machine has a different ipaddress than the local ip(127.0.0.1)

**Comment by samgomena** [comment]
Can you try running the following on your machine and see what it yields:
```python
import socket
sock = socket.socket(socket.AF_INET, socket.DGRAM)
sock.connect(('8.8.8.8', 443))
ip_addr = sock.getsockname()[0]
print(ip_addr)
```

**Comment by susham** [comment]
I have run the python script and it works fine in the Ubuntu 18.04
It gave a different ipaddress than the 127.0.0.1
